# Generated by Django 5.2.17 on 2026-08-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Form Status')),
                ('opening_date', models.DateField(blank=True, null=True, verbose_name='Opening Date')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='Opening Time')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='Closing Date')),
                ('closing_time', models.TimeField(blank=True, null=True, verbose_name='Closing Time')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Form Settings',
                'verbose_name_plural': 'Form Settings',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of the Student')),
                ('enrollment_number', models.CharField(max_length=50, unique=True, verbose_name='Enrollment Number')),
                ('exam_registration_number', models.CharField(max_length=50, unique=True, verbose_name='Exam Registration Number')),
                ('umis_number', models.CharField(max_length=50, unique=True, verbose_name='UMIS Number')),
                ('program_of_study', models.CharField(choices=[('B.E.', 'B.E. (Bachelor of Engineering)'), ('B.Tech.', 'B.Tech. (Bachelor of Technology)'), ('M.E.', 'M.E. (Master of Engineering)'), ('M.Tech.', 'M.Tech. (Master of Technology)'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('Other', 'Other')], max_length=100, verbose_name='Program of Study')),
                ('branch', models.CharField(choices=[('Civil Engineering', 'Civil Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Electrical & Electronics Engineering', 'Electrical & Electronics Engineering'), ('Electronics & Communication Engineering', 'Electronics & Communication Engineering'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Information Technology', 'Information Technology'), ('Chemical Engineering', 'Chemical Engineering'), ('Aeronautical Engineering', 'Aeronautical Engineering'), ('Automobile Engineering', 'Automobile Engineering'), ('Biomedical Engineering', 'Biomedical Engineering'), ('Biotechnology', 'Biotechnology'), ('Agriculture Engineering', 'Agriculture Engineering'), ('Artificial Intelligence & Data Science', 'Artificial Intelligence & Data Science'), ('Artificial Intelligence & Machine Learning', 'Artificial Intelligence & Machine Learning'), ('Cyber Security', 'Cyber Security'), ('Other', 'Other')], max_length=100, verbose_name='Discipline/Branch')),
                ('year_of_completion', models.IntegerField(verbose_name='Year of Completion')),
                ('email', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('mobile', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('alternate_mobile', models.CharField(blank=True, max_length=15, verbose_name='Alternate Mobile Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Gender')),
                ('category', models.CharField(choices=[('OC', 'OC (Open Category)'), ('BC', 'BC (Backward Class)'), ('BC(M)', 'BC(M) (Backward Class Muslim)'), ('MBC', 'MBC (Most Backward Class)'), ('SC', 'SC (Scheduled Caste)'), ('SCA', 'SCA (Scheduled Caste Arunthathiyar)'), ('ST', 'ST (Scheduled Tribe)')], max_length=20, verbose_name='Category (Community)')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='Blood Group')),
                ('pan_number', models.CharField(blank=True, max_length=10, verbose_name='PAN Number')),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, verbose_name='Aadhaar Number')),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='Passport Number')),
                ('permanent_address', models.TextField(verbose_name='Permanent Address')),
                ('guardian_name', models.CharField(max_length=200, verbose_name="Father's/Guardian's Name")),
                ('guardian_mobile', models.CharField(max_length=15, verbose_name="Father's/Guardian's Mobile Number")),
                ('guardian_occupation', models.CharField(max_length=200, verbose_name="Father's/Guardian's Occupation")),
                ('guardian_annual_income', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Father's/Guardian's Annual Income")),
                ('tenth_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='10th Pass Percentage')),
                ('tenth_passing_year', models.IntegerField(verbose_name='Year of 10th Passing')),
                ('twelfth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='12th Pass Percentage')),
                ('twelfth_passing_year', models.IntegerField(blank=True, null=True, verbose_name='Year of 12th Passing')),
                ('diploma_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Diploma Pass Percentage')),
                ('diploma_passing_year', models.IntegerField(blank=True, null=True, verbose_name='Year of Passing Diploma')),
                ('ogpa', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='OGPA (Till 5th Semester)')),
                ('history_of_arrears', models.BooleanField(default=False, verbose_name='History of Arrears')),
                ('current_backlog', models.BooleanField(default=False, verbose_name='Current Backlog (Standing Arrears)')),
                ('number_of_backlogs', models.IntegerField(default=0, verbose_name='Number of Backlogs')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks / Year Gap Reason')),
                ('programming_languages', models.TextField(blank=True, verbose_name='Programming Languages Known')),
                ('communication_languages', models.TextField(blank=True, verbose_name='Communication (Spoken) Languages Known')),
                ('additional_skills', models.TextField(blank=True, verbose_name='Additional Skill Set')),
                ('internship_company', models.CharField(blank=True, max_length=300, verbose_name='Internship Company')),
                ('internship_dates', models.CharField(blank=True, max_length=200, verbose_name='Internship Dates')),
                ('laptop_desktop', models.BooleanField(default=False, verbose_name='Laptop/Desktop with Webcam & Mic')),
                ('high_speed_internet', models.BooleanField(default=False, verbose_name='High-Speed Internet Connection')),
                ('career_preference', models.CharField(choices=[('Campus Placement', 'Campus Placement'), ('Higher Studies', 'Higher Studies'), ('Entrepreneurship', 'Entrepreneurship'), ('Campus Placement & Higher Studies', 'Campus Placement & Higher Studies'), ('All', 'All')], max_length=100, verbose_name='Career Preference')),
                ('willingness_to_relocate', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Depends on Location', 'Depends on Location')], max_length=30, verbose_name='Willingness to Relocate')),
                ('nptel_courses', models.TextField(blank=True, verbose_name='NPTEL/SWAYAM Courses Completed')),
                ('future_internship', models.BooleanField(default=False, verbose_name='Willing for Internship (Dec 2026 - Apr 2027)')),
                ('tpc_acceptance', models.BooleanField(default=False, verbose_name='TPC Rules Acceptance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
    ]
